- package-lock.json
- package.json
- src/App.tsx
- src/components/SortableTable.tsx
- src/components/matchHistory/matchHistoryColumnHelper.tsx
- src/index.tsx
- src/themes/amethyst/components/alert.ts
- src/themes/amethyst/components/button.ts
- src/themes/amethyst/components/heading.ts
- src/themes/amethyst/components/table.ts
- src/themes/amethyst/components/tabs.ts
- src/themes/amethyst/components/tag.ts
- src/themes/amethyst/components/text.ts
- src/themes/amethyst/index.ts
- src/themes/utils.ts
- src/types/domain/Match.ts
- src/types/domain/MatchPlayer.ts
- src/types/service/dataMappers.ts
This PR adds in the service and domain types, does the service call to the google sheets api to get the data, and pulls in the SortableTable component to show the hydrated data. 
I also added in the chakra styles to make things look correct. 
The SortableTable and chakra styles come from a separate project (mnc-frontend)
> Add styles, domain types, and basic service call to get data

- src/components/matchHistory/MatchDetails.tsx
- src/components/matchHistory/MatchHistory.tsx
- src/navigation/routes.tsx
- src/redux/statsSelectors.ts
Add the ability to see match details, as well as enable navigation from match history to match details.
Placeholder images for commanders for now.
> Add the ability to see match details

- src/components/commanderOverview/CommanderOverview.tsx
Added loading text to commander overview page
> Added loading text to Commander Overview page

- src/components/commanderOverview/commanderOverviewColumnHelper.tsx
- src/components/home/Home.tsx
Update the logo on the home page and add commander images to commander overview
> Update the logo on the home page and add commander images to commander overview

- src/components/SidebarWithHeader.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/matchHistory/MatchHistory.tsx
1. match history in reverse chronological order
2. commanders list in alphabetical
> Revise the order of things

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/commanderOverview/commanderOverviewColumnHelper.tsx
- src/redux/statsReducer.ts
- src/types/domain/Commander.ts
Added "Qualified"** field on the commander details page.
Added "Show only qualified**" checkbox filter to commander overview page.
** "Qualified" means matches over 5 times.
> Added qualified field and checkbox

- package-lock.json
- package.json
- src/components/commanderOverview/CommanderDetails.tsx
Add in support for graphs, add winrate graph to commander details
> Add in support for graphs, add winrate graph to commander details

- src/components/commanderOverview/CommanderDetails.tsx
Do not show graph when there are less than 5 games for commander
> Do not show graph when there are less than 5 games for commander

- public/manifest.json
- src/components/BarGraph.tsx
- src/components/LineGraph.tsx
- src/components/commanderOverview/CommanderDetails.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/matchHistory/MatchDetails.tsx
- src/components/matchTrends/CommandersPlayedChart.tsx
- src/components/matchTrends/MatchLengthBarChart.tsx
- src/components/matchTrends/MatchLengthLineChart.tsx
- src/components/playerOverview/playerOverview.tsx
- src/themes/acorn/index.ts
I updated our themes so that anywhere in the app we can refer to our shared theme's colors. 
Also stood up new lineChart and barChart components so they are more easily used than directly using chartjs components. 
I updated the MatchTrends to use these new components.
> Revise graph colors, create new shared bar and line graph components.

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/matchHistory/MatchDetails.tsx
- src/components/matchHistory/matchHistoryColumnHelper.tsx
- src/components/matchTrends/CommandersPlayedChart.tsx
- src/redux/statsReducer.ts
- src/redux/statsSelectors.ts
- src/types/domain/MatchPlayer.ts
- src/types/service/dataMappers.ts
This change supports the idea of partner commanders. The delimiter for partner commanders is " && ".
> Players can now have 2 commanders

- src/components/playerOverview/PlayerDetails.tsx
- src/redux/statsReducer.ts
- src/tools/Janus.html
Commander history now sorted by most played commander
> Sorted player details commander history

- src/components/commanderOverview/CommanderDetails.tsx
- src/redux/statsSelectors.ts
- src/types/domain/MatchPlayer.ts
Shows players who play each commander + matches + winrate
> Add "Top Players" to commander details page

- rome.json
to allow up to 120 characters in a line
> Update ROME settings

- src/components/matchHistory/MatchDetails.tsx
- src/components/matchHistory/MatchPlayerCard.tsx
- src/components/matchHistory/MatchPlayerImage.tsx
- src/components/matchHistory/matchHistoryColumnHelper.tsx
- src/components/matchHistory/types/MatchDisplayCommander.ts
- src/components/matchHistory/types/MatchDisplayPlayer.ts
- src/redux/statsSelectors.ts
Add support for multiple commanders in the match details. Reorganized match details components and types
> Match details file organization and partner support

- src/components/SidebarWithHeader.tsx
- src/components/home/Home.tsx
- src/components/home/HomeNewsSection.tsx
- src/services/featureFlagService.ts
Hide the news section in navigation and home based on this feature flag
> Add support for feature flags

- src/components/playerOverview/PlayerDetails.tsx
Changed "favorite commander" data from text link to image link + hover
> PlayerDetails - fav commander updates

- src/components/matchHistory/MatchPlayerCard.tsx
- src/components/playerOverview/PlayerDetails.tsx
2 bugs in dev right now are breaking the app. 
1. player details tries to load favorite commander before data is hydrated
2. match details does not properly navigate to individual players (casing issue)
> Fix 2 breaking bugs

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/constants.ts
- src/components/dataVisualizations/PieGraph.tsx
- src/components/matchHistory/MatchPlayerCard.tsx
- src/components/playerOverview/PlayerDetails.tsx
- src/logic/dictionaryUtils.ts
- src/redux/statsReducer.ts
- src/redux/statsSelectors.ts
- src/types/domain/Commander.ts
- src/types/domain/Player.ts
Added color pie and reformatted header
> Add color pie to the player details and add color identity to commander/player objects.

- src/components/dataVisualizations/PieGraph.tsx
> Color pie tooltip updated

- src/components/playerOverview/PlayerDetails.tsx
use max sizes instead of specific sizes, use flex wrap to handle mobile better
> Fix player details for mobile style

- public/index.html
we only want this in the prod repo
> Remove gtag code from dev repo

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/common/DatePicker.tsx
- src/logic/dictionaryUtils.ts
- src/redux/statsSelectors.ts
create date picker for commander details/overview
update dictionary utils to support date filtering
> create date picker for commander details/overview

- src/components/playerOverview/PlayerDetails.tsx
Fix discrepancy in player winrate overview vs details
> Fix discrepancy in player winrate overview vs details

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/playerOverview/PlayerDetails.tsx
- src/components/playerOverview/PlayerOverview.tsx
- src/logic/utils.ts
- src/redux/statsSelectors.ts
Also add utils to consistently compute win rate. 
Player details was using some locally computed data instead of the player data we get from the "main" player we saved in state.
> Add date filter to player details and player overview

- src/components/matchTrends/MatchTrends.tsx
Moved colors played to match trends
If this PR is accepted, will delete other PR
> Colors played added to match trends

- src/components/matchHistory/MatchDetails.tsx
- src/components/matchHistory/MatchPlayerCard.tsx
- src/components/matchHistory/MatchSubmission.tsx
- src/components/matchHistory/types/MatchDisplayPlayer.ts
- src/services/matchHistoryService.ts
1. Fix navigation issue on match details page
2. Swap to radio buttons on match submission
3. Fix mislabled property in match submission in service
> Misc fixes

- .vscode/settings.json
- biome.json
- src/components/matchTrends/MatchLengthBarChart.tsx
- src/components/matchTrends/MatchTrends.tsx
Update personal formatting settings and remove unused imports
> Housekeeping changes

- .prettierrc
- biome.json
Remove biome, tell prettier to remove trailing comma
> Update formatter settings

- src/components/SidebarWithHeader.tsx
- src/components/commanderOverview/CommanderDetails.tsx
> Fix styling on the commander details page

- src/components/matchHistory/MatchDetails.tsx
- src/components/matchHistory/MatchPlayerCard.tsx
- src/components/matchHistory/MatchPlayerImage.tsx
> Update styles on the match details page

- src/components/matchHistory/MatchSubmission.tsx
Checkbox in chakra is not keyboard accessible.
> Swap match submission checkbox with a toggle button

- src/services/commanderList.ts
> Support WHO

- src/components/playerOverview/CommanderMatchupsTable.tsx
- src/components/playerOverview/PlayerMatchupsTable.tsx
- src/components/playerOverview/playerDetails/PlayerDetails.tsx
Was not using "in focus" player
> Fix math in calculating matchups

- src/components/constants.ts
- src/logic/utils.ts
adding a new function to support highlighting new players in playeroverview
> highlighting new players function

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/dataVisualizations/columnHelpers/playerOverviewColumnHelper.tsx
- src/components/dataVisualizations/columnHelpers/topPlayersColumnHelper.tsx
- src/logic/utils.ts
Add the new players tag for the player overview table:
> Add support for new players flag in the players overview table

- src/components/auth/LoginModal.tsx
- src/components/auth/SettingsModal.tsx
- src/components/navigation/AppFrame.tsx
- src/components/navigation/Header.tsx
- src/components/navigation/Sidebar.tsx
- src/components/playerOverview/playerDetails/PlayerDetailsInfoCard.tsx
- src/logic/hooks/authHooks.ts
- src/logic/hooks/userHooks.ts
- src/navigation/routes.tsx
- src/services/DiscordService.ts
- src/services/ProfileService.ts
Spinning up the login flows was pretty messy, so this goes in and cleans up a lot of the code to make sure we follow conventions. 
Created a new "hooks" directory in logic that we'll move more hooks into to make selector usage a little bit cleaner.
> Code clean up for login related logic and components

- src/logic/utils.test.ts
- src/logic/utils.ts
getWinRatePercentage function got an overhaul:
It now accepts decimal places as an additional argument. It also handles most errors by logging an error message and outputting -1 as the result. This -1 will be visible to the end user if something goes wrong.
Added a bunch of test cases to utils.test.ts as well.
> "getWinratePercentage": support for user defined decimal places

- package.json
- src/components/auth/SettingsModal.tsx
- src/types/domain/Profile.ts
- src/types/service/ProfileService/ChatterfangProfile.ts
- src/types/service/ProfileService/dataMappers.ts
Will split this feature into 3-4 PRs
If this PR goes through, next PR will be actually updating the data on Chatterfang with the input provided (no validation, yet) and displaying the results
Then next PR will be validation
> Moxfield ID: button added, types updated

- src/components/auth/SettingsModal.tsx
- src/components/commanderOverview/CommanderDetails.tsx
- src/components/dataVisualizations/columnHelpers/matchHistoryColumnHelper.tsx
- src/components/dataVisualizations/columnHelpers/playerOverviewColumnHelper.tsx
- src/components/playerOverview/playerDetails/PlayerDetailsInfoCard.tsx
Consolidate winrate + win count into a single number & add number of turns to match history
> Consolidate winrate + win count into a single number & add number of turns to match history

- src/logic/dictionaryUtils.ts
- src/services/commanderList.ts
- src/tools/Janus.html
Also update some the color_identity naming to make it follow conventions.
> Update janus to support commander name and scryfall uri

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/matchTrends/MatchPositionWinsBarChart.tsx
- src/components/matchTrends/MatchTrends.tsx
- src/components/playerOverview/CommanderMatchupsTable.tsx
- src/components/playerOverview/PlayerMatchupsTable.tsx
- src/components/playerOverview/playerDetails/PlayerDetailsInfoCard.tsx
Also add in scryfall external link, and some light cleanup in places
> Add new match trends table for table position wins & small updates

- src/components/auth/SettingsModal.tsx
- src/services/MoxfieldService.ts
- src/types/domain/MoxfieldProfile.ts
- src/types/service/MoxfieldService/MoxfieldResponse.ts
Does NOT yet handle moxfield users without a profile picture
> Moxfield id GET from Chatterfang

- src/components/auth/SettingsModal.tsx
- src/components/dataVisualizations/PieGraph.tsx
- src/services/ProfileService.ts
> Moxfield IDs - Part 2: POST to Chatterfang

- src/components/home/Home.tsx
- src/components/home/HomeNewsSection.tsx
- src/components/navigation/Sidebar.tsx
- src/components/news/NewsDetail.tsx
Adjusting some light styles and fixing some of the places i missed renaming of "articles" to "updates".
> Clean up the styling of "updates"

- src/services/MatchHistoryService.ts
The match history submit URL was accidentally replaced with the match history get URL.
> Add back in the correct match history submit endpoint

- src/services/ProfileService.ts
Add some additional linked profiles.
> Add some additional profile links

- src/articles/Article_9.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/dataVisualizations/columnHelpers/matchHistoryColumnHelper.tsx
- src/components/news/NewsCard.tsx
- src/components/news/NewsCards.tsx
- src/components/playerOverview/PlayerOverview.tsx
- src/logic/utils.ts
- src/services/ProfileService.ts
make sure the match table information wraps, and indents on the second line.
also fix the "new" player tag calculation
clean up the styling on the news cards to use chakra elements instead of raw html
> Various styling fixes

- public/index.html
> Count goats

- src/components/playerOverview/playerDetails/PlayerDecks.tsx
Reorder and resize deck cards UI for Player Details page
> Moxfield decks UI changes for Player Details page

- src/components/playerOverview/playerDetails/PlayerDecks.tsx
- src/components/playerOverview/playerDetails/PlayerDetails.tsx
- src/components/playerOverview/playerDetails/PlayerDetailsInfoCard.tsx
1. linked moxfield accounts now open on new tab instead of same window
2. fix alignment on player decks section
> Do some small fixes for the march update

- src/components/matchTrends/MatchLengthLineChart.tsx
- src/services/commanderList.ts
- src/tools/Janus.html
Also add average match length to match trends table. 
fix janus to properly handle some commanders with quotation marks in their name
> Update commander list for fallout set

- src/components/matchTrends/MatchTimeLineChart.tsx
Fixing a bug in the match time chart.
> Wrong scale and data for time length chart

- src/components/commanderOverview/CommanderMatchupsTable.tsx
- src/services/GoogleFormsService.ts
- src/services/MatchHistoryService.ts
Add new fields to match submission- fix bug in commander matchups in commander details page
> Add new fields to match submission & fix commander matchups bug

- src/components/commanderOverview/CommanderDetails.tsx
- src/logic/dictionaryUtils.ts
- src/services/commanderList.ts
Pull in support for mh3
small fix to properly order matches by match id by default
small fix to properly support "min number of players" (before it was looking for exactly that number vs anything larger than that number)
> Pull in support for mh3

- src/components/commanderOverview/CommanderDetails.tsx
- src/components/commanderOverview/CommanderMatchupsTable.tsx
- src/components/commanderOverview/CommanderOverview.tsx
- src/components/commanderOverview/PlayerMatchupsTable.tsx
- src/components/commanderTrends/CommanderTrends.tsx
- src/components/common/DatePicker.tsx
- src/components/matchTrends/MatchTrends.tsx
- src/components/playerOverview/CommanderHistoryTable.tsx
- src/components/playerOverview/PlayerOverview.tsx
- src/components/playerOverview/playerDetails/PlayerDetails.tsx
Various styling cleanups around the datepicker, as well as adding it to a few more pages for easy reference/updates. 
We'll likely move the date picker to the top nav as this is something that users will want to be able to filter/change across any page.
> Various cleanups around the date picker
